### ISSUE TITLE
Compiling flags

### ISSUE THREAD

**Issue by lue** [rainwoodman/fastpm#28]
Hi!

I was trying to compile FastPM from the repository on a new Linux machine.

In order to compile pfft without errors, I added -std=c99 flag in Makefile.local:
`OPTIMIZE = -O3 -g -std=c99`

But then bigfile compilation broke down:

```
../depends/libfastpm-dep.a(libbigfile-mpi.a-bigfile-mpi.o): In function `big_file_mpi_broadcast_error':
/home/kaurov/soft/fastpm_test/depends/bigfile/bigfile-mpi.c:195: undefined reference to `alloca'
../depends/libfastpm-dep.a(libbigfile-mpi.a-bigfile-mpi.o): In function `big_file_mpi_open_block':
/home/kaurov/soft/fastpm_test/depends/bigfile/bigfile-mpi.c:65: undefined reference to `alloca'
../depends/libfastpm-dep.a(libbigfile-mpi.a-bigfile-mpi.o): In function `big_file_mpi_create_block':
/home/kaurov/soft/fastpm_test/depends/bigfile/bigfile-mpi.c:91: undefined reference to `alloca'
../depends/libfastpm-dep.a(libbigfile-mpi.a-bigfile-mpi.o): In function `big_block_mpi_close':
/home/kaurov/soft/fastpm_test/depends/bigfile/bigfile-mpi.c:161: undefined reference to `alloca'
collect2: error: ld returned 1 exit status
make[1]: *** [fastpm] Error 1
```

According to http://man7.org/linux/man-pages/man3/alloca.3.html

> Notes on the GNU version
>        Normally, gcc(1) translates calls to alloca() with inlined code.
>        This is not done when either the -ansi, -std=c89, -std=c99, or the
>        -std=c11 option is given and the header <alloca.h> is not included.
> 

Therefore, I added to depends/bigfile/bigfile-mpi.c and depends/bigfile/bigfile.c

```
#include <malloc.h>
#include <alloca.h>
```

Everything worked after this addition. 

Not sure, whether I messed up with the Makefile.local or these libraries should be indeed added to those two files.

**Comment by rainwoodman** [comment]
These should be added to the files. I will update them soon. Thank!
