### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by DriftingPig** [rainwoodman/fastpm#29]
Hello,
I'm trying to install fastPM on NERSC, but it doesn't seem to work in both ways (I tried the first two ways). 

I followed the installation guide on the 'Source Code Installation' section. 
For the first way, 

module load gsl 
cp Makefile.local.example Makefile.local 
make 

it just get stuck in the 'make' command, and the system get timed out and exited. 

Then I tried the second way: 
module load python/2.7-anaconda 
conda create -n cfastpm numpy 
source activate cfastpm 
conda install -c bccp cfastpm nbodykit 

It gives me the following error: 
Using Anaconda Cloud api site https://api.anaconda.org 
Fetching package metadata ......... 
Solving package specifications: . 
Error: Dependencies missing in current linux-64 channels: 
- cfastpm -> libgcc-ng >=7.2.0 
- nbodykit -> halotools -> libgcc-ng >=7.2.0 
- nbodykit -> halotools -> libstdcxx-ng >=7.2.0 
- nbodykit -> halotools -> numpy >=1.13.3,<2.0a0 
- nbodykit -> mpsort -> @mpich2 -> libgfortran-ng >=7,<8.0a0 

Close matches found; did you mean one of these? 

libgcc-ng: libgcc 
libgfortran-ng: libgfortran 

You can search for packages on anaconda.org with 

anaconda search -t conda numpy 

(and similarly for the other packages) 

Can you tell me how to deal with the error, or how to install the software? 

By the way, I asked this question to the NERSC online help desk, and here's their current reply:
Still working on getting it to install from source. So apparently they are redirecting configure and make install output from one of fastpm's dependencies which makes it look like it's hanging (tee was not working like it was suppose to). I'm able to get through but I'm getting linking errors with GSL. Apparently it's not being added to CFLAGS and LDFLAGS. Might be worth it to submit a github issue. In the mean time, I'm still trying to work out the linking errors. 

Thanks,
Hui

**Comment by rainwoodman** [comment]
====== case 1 =====
Sorry for the mess -- do you see any output when it stuck in the make
command? compiling the FFT library may take a very long time (depending if
the NERSC home file system is choking from 5 to 15 mins).

It will stay here for a very long time:

```
touch
/global/u1/y/yfeng1/source/fastpm/depends/src/pfft-1.0.8-alpha2-fftw3/configure
mkdir -p double;
(cd double; \
/global/u1/y/yfeng1/source/fastpm/depends/src/pfft-1.0.8-alpha2-fftw3/configure
--prefix=/global/u1/y/yfeng1/source/fastpm/depends/install --disable-shared
--enable-static  \
--disable-fortran --disable-doc --enable-mpi --enable-sse2 --enable-avx
--enable-openmp "MPICC=cc" \
2>&1 ; \
make -j 4 2>&1 ; \
make install 2>&1; \
) | tee pfft-double.log | tail
```

Here is my makefile.local on nersc.
```
CC=cc
CPPFLAGS = -DFASTPM_FFT_PRECISION=32
OPTIMIZE ?= -O3 -g
GSL_LIBS = $(GSL)
CPPFLAGS = -I$(GSL_DIR)/include
```

after module load gsl this should get most of the work done.

====== case 2 =====
The conda channel binaries requires anaconda 5.x due to a bug in conda that
they fixed fairly recently regarding the cross compilation tools
change(libgcc-ng stuff you see). I've been asking NERSC to deploy a newer
version of anaconda without any success yet.

For now you can try activating the one we use:
```
source /usr/common/contrib/bccp/anaconda3/bin/activate

```

**Comment by rainwoodman** [comment]
more to case 2 -- so apparently only 2.7-anaconda is old enough that it
doesn't work.

```
yfeng1@edison03:~> module swap python python/3.6-anaconda-4.4
yfeng1@edison03:~> conda create -n cfastpm -c bccp cfastpm
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.7
  latest version: 4.4.11

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /global/homes/y/yfeng1/.conda/envs/cfastpm

  added / updated specs:
    - cfastpm


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mpich2-1.4.1p1             |                0         2.7 MB
    cfastpm-0.0.0_git8442714   |       h49e5514_4         1.4 MB  bccp
    ------------------------------------------------------------
                                           Total:         4.1 MB

The following NEW packages will be INSTALLED:

    cfastpm:   0.0.0_git8442714-h49e5514_4 bccp
    gsl:       2.2.1-h0c605f7_3
    libgcc-ng: 7.2.0-h7cc24e2_2
    mpich2:    1.4.1p1-0

Proceed ([y]/n)? y

```

**Comment by DriftingPig** [comment]
Hi,
I tried Both cases again. 
====case 1====
I got the following errors:
.....
) | tee pfft-double.log | tail
for case1, this time I got the errors as below:
for(int t=0; t<ths->rnk; t++)
                   ^

compilation aborted for /global/u2/h/huikong/fastPM/fastpm/depends/src/pfft-1.0.8-alpha3-fftw3/kernel/ousample.c (code 2)
Makefile:442: recipe for target 'ousample.lo' failed
make[4]: *** [ousample.lo] Error 1
make[4]: Leaving directory '/global/u2/h/huikong/fastPM/fastpm/depends/single/kernel'
Makefile:642: recipe for target 'install-recursive' failed
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory '/global/u2/h/huikong/fastPM/fastpm/depends/single'
make[2]: Leaving directory '/global/u2/h/huikong/fastPM/fastpm/depends'
../ar-join libfastpm-dep.a install/lib/libbigfile.a install/lib/libbigfile-mpi.a install/lib/libradixsort.a install/lib/libmpsort-mpi.a install/lib/libfftw3.a install/lib/libfftw3_mpi.a install/lib/libfftw3_omp.a install/lib/libfftw3f.a install/lib/libfftw3f_mpi.a install/lib/libfftw3f_omp.a install/lib/libpfft_omp.a install/lib/libpfftf_omp.a
Adding install/lib/libbigfile.a to libfastpm-dep.a ...
Adding install/lib/libbigfile-mpi.a to libfastpm-dep.a ...
Adding install/lib/libradixsort.a to libfastpm-dep.a ...
Adding install/lib/libmpsort-mpi.a to libfastpm-dep.a ...
Adding install/lib/libfftw3.a to libfastpm-dep.a ...
Adding install/lib/libfftw3_mpi.a to libfastpm-dep.a ...
Adding install/lib/libfftw3_omp.a to libfastpm-dep.a ...
Adding install/lib/libfftw3f.a to libfastpm-dep.a ...
Adding install/lib/libfftw3f_mpi.a to libfastpm-dep.a ...
Adding install/lib/libfftw3f_omp.a to libfastpm-dep.a ...
Archive file install/lib/libpfft_omp.a not found.
Makefile:34: recipe for target 'libfastpm-dep.a' failed
make[1]: *** [libfastpm-dep.a] Error 1
make[1]: Leaving directory '/global/u2/h/huikong/fastPM/fastpm/depends'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2


====case 2====
I swapped python and made a new environment, then I tried:
conda install -c bccp cfastpm nbodykit

It works smoothly until the end. However, nbodykit and cfastpm doesn't seem to be installed there. When I open python and tried to import nbodykit, it says that it doesn't exist. 

Below are the information I got. Do you know why they aren't imported?

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.7
  latest version: 4.4.11

Please update conda by running
    $ conda update -n base conda



## Package Plan ##

  environment location: /global/homes/h/huikong/.conda/envs/cfastpm

  added / updated specs: 
    - cfastpm
    - nbodykit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mcfit-0.0.7                |   py36h1004ed8_0          17 KB  bccp
    cffi-1.11.5                |   py36h9745a5d_0         212 KB
    yaml-0.1.7                 |       had09818_2          85 KB
    ------------------------------------------------------------
                                           Total:         314 KB

**Comment by rainwoodman** [comment]
=== case 1 ===
Take a look which compiler you are using? It worked fine here (on commit
987b2d9, which is pretty close to the head of master).
```
yfeng1@edison08:~/source/fastpm> module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.6
  2) nsg/1.2.0
  3) cray-mpich/7.6.2
  4) gcc/7.1.0
  5) craype-ivybridge
  6) craype-network-aries
  7) craype/2.5.12
  8) cray-libsci/17.09.1
  9) udreg/2.3.2-6.0.4.0_12.2__g2f9c3ee.ari
 10) ugni/6.0.14-6.0.4.0_14.1__ge7db4a2.ari
 11) pmi/5.0.12
 12) dmapp/7.1.1-6.0.4.0_46.2__gb8abda2.ari
 13) gni-headers/5.0.11-6.0.4.0_7.2__g7136988.ari
 14) xpmem/2.2.2-6.0.4.1_18.2__g43b0535.ari
 15) job/2.2.2-6.0.4.0_8.2__g3c644b5.ari
 16) dvs/2.7_2.2.36-6.0.4.1_16.2__g4c8274a
 17) alps/6.4.1-6.0.4.0_7.2__g86d0f3d.ari
 18) rca/2.2.15-6.0.4.1_13.1__g46acb0f.ari
 19) atp/2.1.1
 20) PrgEnv-gnu/6.0.4
 21) gsl/2.3
```

=== case 2 ====

I suspect you didn't install python to the environment -- so you are likely
running a python where nbodykit is not even installed? To use the kernel on
jupyter-dev.nersc.gov you'll need to install ipython and notebook as well.

Also, it appears at least the package for nbodykit is not even downloaded?
What is the output of `conda list`?

**Comment by DriftingPig** [comment]
The conda method works now, thanks a lot!
Then I tried running an example in fastpm/Examples/nbodykit.ipynb, it worked well until the command:
mpirun -n 4 ../src/fastpm nbodykit.lua
which gives me the error:
[proxy:0:0@cori06] HYDU_create_process (../../utils/launch/launch.c:825): execvp error on file ../src/fastpm (No such file or directory)
[proxy:0:0@cori06] HYDU_create_process (../../utils/launch/launch.c:825): execvp error on file ../src/fastpm (No such file or directory)
[proxy:0:0@cori06] HYDU_create_process (../../utils/launch/launch.c:825): execvp error on file ../src/fastpm (No such file or directory)
[proxy:0:0@cori06] HYDU_create_process (../../utils/launch/launch.c:825): execvp error on file ../src/fastpm (No such file or directory)

And there's really no file called fastpm in ../src. I guess this command works for the one compiled with 'make', where you can generate some exactable file? What should I want to use a similar command, and I used conda to install it?

Thanks,
Hui

**Comment by rainwoodman** [comment]
If you install cfastpm with the conda method, the binary fastpm should be on the path. see what happens if you run `which fastpm`.

**Comment by DriftingPig** [comment]
I see. I can run the code by just running:
mpirun -n 4 fastpm nbodykit.lua
And it works now. 
Thank you!
