### ISSUE TITLE
floating exception in fof

### ISSUE THREAD

**Issue by ColdThunder** [rainwoodman/fastpm#51]
I got "Killed by Signal 8" in fof.c
I use print debug to find the place.  It happens at libfastpm/store.c, in function "fastpm_store_get_q_from_id"
id = id % p->meta._q_size,

here p->meta._q_size=0

**Comment by rainwoodman** [comment]
could you post the full back trace? it seems to be an easy bug due to the
new multi species support. also which version of code are you running?

**Comment by rainwoodman** [comment]
I see you used 'print debug'. So there is not back trace. Useful is the
stdout log, then I can tell which module triggered this, and probably try
to reproduce the bug locally and get a trace.

**Comment by ColdThunder** [comment]
[fof.log](https://github.com/rainwoodman/fastpm/files/3043573/fof.log)
=======================
This happens when I run "fastpm-fof", not "fastpm"
=======================
The run is killed by signal 8, in [libfastpm/fof.c].
In the function "fastpm_fof_execute",
function "fastpm_fof_compute_halo_attrs(finder, halos, head, _convert_basic_halo_attrs, _add_basic_halo_     attrs, _reduce_basic_halo_attrs);" is called.
It uses "convert_basic_halo_attrs,",
and it calls "fastpm_store_get_q_from_id" in [libfastpm/store.c] file.
In "fastpm_store_get_q_from_id"  it calculates "id = id % p->meta._q_size,", and at this time p->meta._q_size=0
=======================
I just realized that both executable "fastpm" and "fastpm-fof" in generated, and "fastpm" also finds haloes.  Thus I do not need to run "fastpm-fof" to find halo.
